sudo: required
services:
  - docker

before_install:
  - docker build -t newtoniumx3/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run newtoniumx3/react-test npm test -- --coverage

after_success:
  - docker build -t newtoniumx3/multi-client ./client
  - docker build -t newtoniumx3/multi-nginx ./nginx
  - docker build -t newtoniumx3/multi-server ./server
  - docker build -t newtoniumx3/multi-worker ./worker
  # push to docker hub
  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push newtoniumx3/multi-client
  - docker push newtoniumx3/multi-nginx
  - docker push newtoniumx3/multi-server
  - docker push newtoniumx3/multi-worker