sudo: required
services:
  - docker
before_install:
  - docker build -t mrassi/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true mrassi/react-test npm test
after_success:
  - docker build -t mrassi/multi-client ./client
  - docker build -t mrassi/multi-nginx ./nginx
  - docker build -t mrassi/multi-server ./server
  - docker build -t mrassi/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mrassi/multi-client
  - docker push mrassi/multi-nginx
  - docker push mrassi/multi-server
  - docker push mrassi/multi-worker